version: '3.8'

services:
  database_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_database_2
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data_2:/var/lib/postgresql/data

  adminer_2:
    image: adminer
    container_name: adminer_2
    restart: always
    env_file: 
      - .env
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  db_data_2:
